insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21833','VD0001','zh','08','克罗姆');
insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21834','VD0001','zh','09','丹东');
insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21835','VD0001','zh','10','苍南');
insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21836','VD0001','zh','11','天信');
insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21837','VD0001','zh','12','重庆前卫');
insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21838','VD0001','zh','13','埃尔斯特');
insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21839','VD0001','zh','14','荣城市宇翔');
insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21840','VD0001','zh','15','罗美特');
insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21841','VD0001','zh','16','贝特');
insert into ss_dict_enum_data( DICT_DATA_ID,DICT_CODE,DICT_LANG,ENUM_CODE,ENUM_VALUE) values('21842','VD0001','zh','17','新立');
/*修改 cm_customer_concat表CONTACT_NAME字段长度为256*/
alter table cm_customer_concat modify column CONTACT_NAME VARCHAR(256);
/*先删除AS_METER_TEMP表*/
drop table AS_METER_TEMP;
/*重新创建AS_METER_TEMP*/
CREATE TABLE `AS_METER_TEMP` (
  `METER_ID` VARCHAR(50) DEFAULT NULL COMMENT '表具编号',
  `ASSET_CODE` VARCHAR(50) DEFAULT NULL COMMENT '资产编号',
  `METER_CODE` VARCHAR(50) DEFAULT NULL COMMENT '表具编号',
  `DC_CODE` VARCHAR(50) DEFAULT NULL COMMENT '集中器编号',
  `CUST_CODE` VARCHAR(50) DEFAULT NULL COMMENT '户号',
  `ASSET_STATE` VARCHAR(50) DEFAULT NULL COMMENT '01：入仓库 02：领用 03：使用中 04：维修 05：报废',
  `METER_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '00：虚拟表计RN            01：电表；RN            02：气表；RN            03：水表；RN            04：热表',
  `METER_TYPENAME` VARCHAR(50) DEFAULT NULL COMMENT '00：虚拟表计RN            01：电表；RN            02：气表；RN            03：水表；RN            04：热表',
  `METER_CATEGORYNAME` VARCHAR(50) DEFAULT NULL COMMENT '表计类型编码（0开头为气表类型定义；1开头为水表类型定义）RN            00：基表；01：RF远程表：02：RF点抄表：03：物联网表：04：IC卡表',
  `MANUFACTURE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '生产厂商',
  `MANUFACTURE_NAME` VARCHAR(50) DEFAULT NULL COMMENT '生产厂商',
  `MODEL_ID` VARCHAR(50) DEFAULT NULL COMMENT '设备型号',
  `MODEL_NAME` VARCHAR(50) DEFAULT NULL COMMENT '设备型号名称',
  `TEMPLATE_NAME` VARCHAR(80) DEFAULT NULL COMMENT '模板名称',
  `DEPT_CODE` VARCHAR(50) DEFAULT NULL COMMENT '所属部门',
  `REGION_CODE` VARCHAR(50) DEFAULT NULL COMMENT '所属楼栋，和计量点的REGION_CODE保持一致',
  `MEASURING_POINT_ID` BIGINT(50) DEFAULT NULL COMMENT '计量点ID，为0时表示还未关联计量点',
  `SIM_NUMBER` VARCHAR(64) DEFAULT NULL COMMENT 'SIM卡号码',
  `RM_TYPE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '01：抄表机抄表     02：远传抄表          03：主动上告     04：人工抄表',
  `RM_TYPE_CODENAME` VARCHAR(50) DEFAULT NULL COMMENT '01：抄表机抄表     02：远传抄表          03：主动上告     04：人工抄表',
  `PAY_TYPE_REAL` VARCHAR(50) DEFAULT NULL COMMENT '真正的付费方式 00：表端预付费  01：后付费 02：预付费，因为预付费的表可以当后付费使用',
  `PAY_TYPE_REALNAME` VARCHAR(50) DEFAULT NULL COMMENT '真正的付费方式 00：表端预付费  01：后付费 02：预付费，因为预付费的表可以当后付费使用',
  `GAS_PROPTYPE` VARCHAR(50) DEFAULT NULL COMMENT '用气性质',
  `GAS_PROPTYPE_NAME` VARCHAR(50) DEFAULT NULL COMMENT '用气性质',
  `ASSET_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '资产类型编码 01：集中器，02：采集器，03：表具',
  `BAR_CODE` VARCHAR(50) DEFAULT NULL COMMENT '资产条形码',
  `EXTERNAL_ASSET_CODE` VARCHAR(50) DEFAULT NULL COMMENT '外部资产编号',
  `COMM_PROTOCOL` VARCHAR(50) DEFAULT NULL COMMENT '通讯规约',
  `COMM_PROTOCOLNAME` VARCHAR(50) DEFAULT NULL COMMENT '通讯规约',
  `REMOTE_COMM_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '01：GPRS/CDMA； 02：3G； 03：4G； 04：SMS（短信）； 05：ITHERNET；',
  `LOCAL_COMM_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '本地通信方式 01：RF组网；  02：RF扩频组网；03：RF点抄；04：RS232(485);  05：WIFI； 06：蓝牙',
  `COMM_ADDR1` VARCHAR(32) DEFAULT NULL COMMENT '通讯地址1',
  `COMM_ADDR2` VARCHAR(32) DEFAULT NULL COMMENT '通讯地址2',
  `COMM_PORT1` VARCHAR(11) DEFAULT NULL COMMENT '通讯端口号1',
  `COMM_PORT2` VARCHAR(11) DEFAULT NULL COMMENT '通讯端口号2',
  `BAUD_RATE` VARCHAR(16) DEFAULT NULL COMMENT '波特率',
  `NETWORK_ID` VARCHAR(20) DEFAULT NULL,
  `FREQUENCY` VARCHAR(10) DEFAULT NULL COMMENT '频点(RF)',
  `APN` VARCHAR(20) DEFAULT NULL COMMENT '网络接入点',
  `area` VARCHAR(20) DEFAULT NULL COMMENT '小区',
  `buildingNumber` VARCHAR(50) DEFAULT NULL COMMENT '楼栋',
  `unitNumber` VARCHAR(20) DEFAULT NULL COMMENT '单元',
  `houseNumber` VARCHAR(20) DEFAULT NULL COMMENT '门牌号码',
  `BOOK_CODE` VARCHAR(50) DEFAULT NULL COMMENT '抄表册编号',
  `STATUS` VARCHAR(10) DEFAULT NULL,
  `CREATOR` VARCHAR(50) DEFAULT NULL COMMENT '操作者',
  `CREATE_DATE` DATE DEFAULT NULL,
  `INDOOR_POSITION` VARCHAR(15) DEFAULT NULL COMMENT '户内安装位置',
  `REMARK` VARCHAR(500) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;
