/*帐户流水表增加字段*/
alter table p_account_log add(PAYER_NAME VARCHAR(50) NULL DEFAULT NULL COMMENT '付款方姓名',
PAYER_BANK_CODE VARCHAR(64) NULL DEFAULT NULL COMMENT '付款行行号');

/*帐户表增加字段*/
alter table p_account add(DEPT_CODE VARCHAR(50) NOT NULL  COMMENT '机构编码');
/*银行对账文件信息表*/
/*序号|交易日期|交易时间|交易日志号|主账号|账户名称|虚拟账号|交易金额|付款账号|付款户名|付款银行行号|付款银行|备注*/
CREATE TABLE `bank_account_log` (
	`LOG_ID` bigint(20) NOT NULL COMMENT '记录Id',
	`ORDER_NUMBER` VARCHAR(50) NOT NULL COMMENT '序号',
	`TRANSACTION_DATE` DATETIME NOT NULL COMMENT '交易日期',
	`TRANSACTION_TIME` DATETIME NOT NULL COMMENT '交易时间',
	`OUT_SERIAL_NUMBER` VARCHAR(50) NOT NULL COMMENT '交易日志号（外部流水号）',
	`PRIMARY_ACNO` VARCHAR(64) NULL DEFAULT NULL COMMENT '主账号',
	`PRIMARY_ACNAME` VARCHAR(64) NULL DEFAULT NULL COMMENT '账户名称',
	`EXTERNAL_ACCOUNT` VARCHAR(100) NOT NULL  COMMENT '虚拟账号',
	`AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '金额',
	`PAYER_ACNO` VARCHAR(50) NOT NULL  COMMENT '付款账号',
	`PAYER_NAME` VARCHAR(50) NOT NULL  COMMENT '付款方姓名',
	`PAYER_BANK_CODE` VARCHAR(64)NOT NULL  COMMENT '付款行行号',
	`PAYER_BANK` VARCHAR(50) NOT NULL  COMMENT '付款银行',
	`OPERATION_TYPE` VARCHAR(2) NOT NULL COMMENT '操作类型 00 充值',
	`REMARK` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
	`CUST_ID` VARCHAR(50) NOT NULL COMMENT '客户ID',
	`DEPT_CODE` VARCHAR(20) NOT NULL COMMENT '部门编码',
	`FILE_NAME` VARCHAR(64) NOT NULL COMMENT '文件名',
	PRIMARY KEY (`OUT_SERIAL_NUMBER`,`TRANSACTION_DATE`,`LOG_ID`)
)
COMMENT='银行对账文件信息表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

/*银行对账文件处理日志表*/
CREATE TABLE `file_process_log` (
	`FILE_NAME` VARCHAR(64) NOT NULL COMMENT '文件名',
	`TOTAL_NUMBER` VARCHAR(64) NULL DEFAULT NULL COMMENT '总笔数：文件说明',
	`TOTAL_MONEY` VARCHAR(64) NULL DEFAULT NULL COMMENT '总金额：文件说明',
	`PROCESS_NUMBER` VARCHAR(64) NULL DEFAULT NULL COMMENT '信息完整数目',
	`WRONG_ENTRY` VARCHAR(2048) NULL DEFAULT NULL COMMENT '信息不完整条目',
	`PROCESS_TIME` DATETIME NOT NULL COMMENT '处理时间',
	`PROCESS_STATUS` VARCHAR(2) NOT NULL COMMENT '处理状态 0失败 1成功',
	PRIMARY KEY (`FILE_NAME`)
)
COMMENT='银行对账文件处理日志表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;



